[dist]
gpg-password-file = "/root/gpg-password"

upload-addr = "http://localhost:9000/static"
upload-bucket = "static"
upload-dir = "dist"

download-bucket = "artifacts"
download-dir = "builds"

aws-access-key-id = "access_key"
aws-secret-key = "secret_key"

aws-s3-endpoint-url = "http://minio:9000"

cloudfront-distribution-id = "id_static"
rustdoc-cf-distribution-id = "id_rustdoc"
