[package]
name = "promote-release"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
curl = "0.4"
flate2 = "0.2"
fs2 = "0.4"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
tar = "0.4"
toml = "0.2"
rand = "0.3"
